name = "CircularBufferArray"
uuid = "00853405-9a93-4ca8-ada5-28e01da65ae5"
authors = ["contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
